language:
- python
python:
- 2.7
install:
# need some stuff system wide
- sudo apt-get update
- sudo apt-get install libreoffice python-pip mercurial default-jdk ant 
  libimage-exiftool-perl gcc

# build mallet
- hg clone http://hg-iesl.cs.umass.edu/hg/mallet
- cd mallet ; ant ; cd ..
- export PATH=mallet/bin:$PATH

# build file/libmagic on travis' 12.04 has problems
- sudo apt-get install gcc
- wget ftp://ftp.astron.com/pub/file/file-5.12.tar.gz
- tar xvfz file-5.12.tar.gz
- cd file-5.12
- ./configure 
- sudo make install
- sudo ldconfig
- cd ..

# now get python requirements
- pip install -r requirements.txt

script:
- python setup.py test 
after_failure:
- cat test.log
