language:
- python
python:
- 2.7
install:
- sudo apt-get update
- sudo apt-get install libreoffice python-pip mercurial default-jdk ant 
  libimage-exiftool-perl libmagic1
- hg clone http://hg-iesl.cs.umass.edu/hg/mallet
- cd mallet ; ant ; cd ..
- export PATH=mallet/bin:$PATH
- pip install -r requirements.txt
script:
- python setup.py test 
after_failure:
- cat test.log
- cat /etc/mime.types
