language:
- python
python:
- 2.7
install:
- sudo apt-get install libreoffice-dev python-pip mercurial default-jdk ant
- hg clone http://hg-iesl.cs.umass.edu/hg/mallet
- cd mallet ; ant ; cd ..
- export PATH=mallet/bin:$PATH
script:
- python setup.py test 


